### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by balla85** [mgueury/html_validator#62] opened 2021-12-10 15:18 UTC
Hi, I obtain the following error message in Console:

"Unchecked runtime.lastError: The message port closed before a response was received."

Maybe the following explanation can help you:

https://support.google.com/chrome/thread/2047906/unchecked-runtime-lasterror-the-message-port-closed-before-a-response-was-received?hl=en

**Comment by mgueury** [comment] 2021-12-10 15:33
Thanks a lot for reporting the issue. I will check the link.

Q1. What should I do to see the issue ? 
Q2. Is it happening randomly or do you see this issue all the time ? 
Q3. Can I have a screenshot ? 

Thanks in advance

**Comment by balla85** [comment] 2021-12-10 15:46
First of all,  I see this error only in chrome; I only saw after that the extension is mainly designed for firefox.

A1. Nothing in particular;
A2. All the time, every page, istantly (at loading?)
A3. Here (e.g. in [nytimescom](https://www.nytimes.com/))
![htmlvalidator](https://user-images.githubusercontent.com/52963782/145601284-044fe555-2ece-4abd-96af-28c013c8d72d.png)

**Comment by esabol** [comment] 2021-12-10 19:01
I see this all the time in Chrome as well, but I've been under the impression that it's caused by my ad blocker extension. @balla85, do you see this with HTML Validator as your only enabled extension?

**Comment by mgueury** [comment] 2021-12-11 14:05
Thanks, I can reproduce it. 

I have the impression that it is related to some recent change in Chrome. The icon on the toolbar that does not get updated anymore neither. This icon change is working with messages. I will check this first.

The same still work in Firefox.

**Comment by balla85** [comment] 2021-12-11 14:38
> I see this all the time in Chrome as well, but I've been under the impression that it's caused by my ad blocker extension. @balla85, do you see this with HTML Validator as your only enabled extension?

Hi, i have several enabled extensions, also Adblock Plus and AdBlock.
But this error message just disappears when I disable HTML Validator.

> Thanks, I can reproduce it.
> 
> I have the impression that it is related to some recent change in Chrome. The icon on the toolbar that does not get updated anymore neither. This icon change is working with messages. I will check this first.
> 
> The same still work in Firefox.

Yes, this error is quite recent, maybe a month, I'm not sure.

**Comment by K-Thompson** [comment] 2021-12-17 10:42
I too get this error. Here's a nice discussion on StackOverflow for a few ways to fix it. Might be as simple as explicitly returning true, from a function.

[How to fix 'Unchecked runtime.lastError](https://stackoverflow.com/questions/54126343/how-to-fix-unchecked-runtime-lasterror-the-message-port-closed-before-a-respon)

**Comment by mgueury** [comment] 2021-12-17 22:32
Thanks @K-Thompson for the tip. That was it. I will publish a version 0.9.9.7 with this fix in a few days.

**Comment by mgueury** [comment] 2021-12-17 22:32
Closing as fixed in 0.9.9.7

**Closed as completed by mgueury** 2021-12-17 22:32 UTC
